[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.deploy]
# Jangan jalankan gunicorn di sini, Railway akan handle sendiri
cmds = []

[start]
# Railway akan menggunakan startCommand dari railway.json